name: Daily fetch script

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '38 13 * * *'
  workflow_dispatch:

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: master
        token: ${{ secrets.PAT }}
  
    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v4
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
    
    - name: Run fetch script
      run: node scripts/fetch.mjs
    
    - name: Run generate index script
      run: node scripts/gen-index.mjs

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: ':robot: fetch articles [skip actions]'
        branch: master
        file_pattern: 'articles files raw-articles'

        commit_user_name: TransportVic
        commit_user_email: 47815427+TransportVic@users.noreply.github.com
        commit_author: TransportVic <47815427+TransportVic@users.noreply.github.com>

    - name: Create temporary directory
      run: mkdir upload; cp -R articles upload; cp -R assets upload; cp -R files upload
      
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        # Upload entire repository
        path: 'upload'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
    